/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_chener_javafx_jni_DrawCall */

#ifndef _Included_xyz_chener_javafx_jni_DrawCall
#define _Included_xyz_chener_javafx_jni_DrawCall
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_addLine
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);


JNIEXPORT void JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_addRectangle
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_addEllipse
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);


JNIEXPORT void JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_addText
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jstring, jfloat, jfloat, jfloat);


JNIEXPORT jfloatArray JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_getColor
  (JNIEnv *, jclass, jint);




JNIEXPORT jint JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_getConcurrentResolvingPower
  (JNIEnv *, jclass);


JNIEXPORT jfloat JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_getButtonSize
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_getShowKey
        (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_xyz_chener_genshinpiano_music_jni_DrawCall_addDrawCallback
  (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif
#endif
